### ISSUE TITLE
PIAA dataset

### ISSUE THREAD

**Issue by GitHub-Ju** [AiArt-Gao/AesMamba#1]
Dear author, your paper is very nice and gives me great inspiration. I have some questions in "train_multi_attr_model_add_human_attr.py" of AesMamba_p. I download PIAA dataset, but I can not find "/PARA/annotation/user/random{random_idx}/user{idx}/train_100shot.csv" and '/data/sjq/IAAdataset/PARA/annotation/user/random{random_idx}/user{idx}/test.csv'. I think this dataset is produced by the author. Can you share this dataset? Thank you very much!

**Comment by JiaqiShi-Stu** [comment]
sorry i,m late.   all right, i will give you later

**Comment by JiaqiShi-Stu** [comment]
[Uploading user.zip…]()

**Comment by GitHub-Ju** [comment]
> Uploading user.zip…
I clicked on this link, but no response.

**Comment by GitHub-Ju** [comment]
Dear author, I clicked on this link, but no response. And, Can you also share Photo.Net dataset? Thank you very much!

**Comment by JiaqiShi-Stu** [comment]
[user.zip](https://github.com/user-attachments/files/17866349/user.zip)

**Comment by JiaqiShi-Stu** [comment]
Pan-Baidu：PhotoNetDataset
Link：https://pan.baidu.com/s/169lvGraBH0LXguebi813mA?pwd=zp5o 
passwd：zp5o

**Comment by GitHub-Ju** [comment]
Thank you very much!
